LOCAL_PATH := $(call my-dir)

ifneq ($(wildcard $(LOCAL_PATH)/FDroid.apk),)
include $(CLEAR_VARS)
LOCAL_MODULE := FDroid
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := FDroid.apk
include $(BUILD_PREBUILT)
endif
