name: red_veil
description: "DARTH CHERRY — night red-light screen filter."
publish_to: 'none'
version: 1.0.2+4

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/darth_cherry.png
