name: polybius_flasher
description: PØLYBÎŪS Android flasher — R36S SD/USB, CRYPT3X OS lite 8GiB, CYD, T-Deck, OTG ADB
publish_to: 'none'
version: 1.6.0+10

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.5
  http: ^1.2.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/firmware/polybius-cyd.bin
    - assets/firmware/polybius-tdeck.bin
    - assets/r36s/polybius-r36s-port.zip
    - assets/r36s/crypt3x-lite.json
    - assets/apks/polybius-v1-stable-hq-android-arm64.apk
    - assets/apks/polybius-v1-stable-user-android-arm64.apk
    - assets/apks/darth-cherry-1.0.2-android-arm64.apk
