/// Second operator wave — 5 admins, 3 developers, 20 users.
///
/// Bootstrapped on first install alongside [OperatorRoster.pool].
/// DEVELOPER / `developer` remains stricken; these are named developer ops.
library;

import 'package:polybius/core/constants/app_constants.dart';
import 'package:polybius/core/constants/operator_roster.dart';

/// Wave-2 seeds (admins / developers / agents).
class OperatorWave2 {
  static const List<OperatorSeed> admins = [
    OperatorSeed(
      username: 'BL4DERUN',
      displayName: 'Bl4deRun',
      inviteCode: 'BR1-77-3R',
      pin: '401122',
      password: 'BladeCut99',
      backupPassword: 'RunBlade7',
      tier: UserTier.admin,
    ),
    OperatorSeed(
      username: 'S0LARF1X',
      displayName: 'S0larF1x',
      inviteCode: 'SF2-77-3R',
      pin: '412233',
      password: 'SolarFix88',
      backupPassword: 'FixSolar3',
      tier: UserTier.admin,
    ),
    OperatorSeed(
      username: 'QU4NTUMOWL',
      displayName: 'Qu4ntumOwl',
      inviteCode: 'QO3-77-3R',
      pin: '423344',
      password: 'OwlQuant1',
      backupPassword: 'QuantOwl9',
      tier: UserTier.admin,
    ),
    OperatorSeed(
      username: 'IRONMER1D',
      displayName: 'IronMer1d',
      inviteCode: 'IM4-77-3R',
      pin: '434455',
      password: 'IronTide42',
      backupPassword: 'MeridIron5',
      tier: UserTier.admin,
    ),
    OperatorSeed(
      username: 'NEONVULT',
      displayName: 'NeonVult',
      inviteCode: 'NV5-77-3R',
      pin: '445566',
      password: 'VultNeon77',
      backupPassword: 'NeonNest2',
      tier: UserTier.admin,
    ),
  ];

  static const List<OperatorSeed> developers = [
    OperatorSeed(
      username: 'C0DERAVEN',
      displayName: 'C0deRaven',
      inviteCode: 'CR1-88-3R',
      pin: '501177',
      password: 'RavenCode9',
      backupPassword: 'CodeNest1',
      tier: UserTier.developer,
    ),
    OperatorSeed(
      username: 'NULLPTRX',
      displayName: 'NullPtrX',
      inviteCode: 'NP2-88-3R',
      pin: '512288',
      password: 'NullSeg88',
      backupPassword: 'PtrNull3',
      tier: UserTier.developer,
    ),
    OperatorSeed(
      username: 'HEXWRAITH',
      displayName: 'HexWraith',
      inviteCode: 'HW3-88-3R',
      pin: '523399',
      password: 'HexGhost7',
      backupPassword: 'WraithHex2',
      tier: UserTier.developer,
    ),
  ];

  static const List<OperatorSeed> users = [
    OperatorSeed(
      username: 'ASHK1TE',
      displayName: 'AshK1te',
      inviteCode: 'U01-55-3R',
      pin: '600101',
      password: 'AshKite11',
      backupPassword: 'KiteAsh2',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'B1TR0VER',
      displayName: 'B1tR0ver',
      inviteCode: 'U02-55-3R',
      pin: '600202',
      password: 'BitRover22',
      backupPassword: 'RoverBit8',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'CRY0MOTH',
      displayName: 'Cry0Moth',
      inviteCode: 'U03-55-3R',
      pin: '600303',
      password: 'CryoMoth3',
      backupPassword: 'MothCryo9',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'DR1FTFOX',
      displayName: 'Dr1ftFox',
      inviteCode: 'U04-55-3R',
      pin: '600404',
      password: 'DriftFox4',
      backupPassword: 'FoxDrift1',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'ECH0LYNX',
      displayName: 'Ech0Lynx',
      inviteCode: 'U05-55-3R',
      pin: '600505',
      password: 'EchoLynx5',
      backupPassword: 'LynxEcho7',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'FLAREM1NT',
      displayName: 'FlareM1nt',
      inviteCode: 'U06-55-3R',
      pin: '600606',
      password: 'FlareMint6',
      backupPassword: 'MintFlare2',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'GL0WWIRE',
      displayName: 'Gl0wWire',
      inviteCode: 'U07-55-3R',
      pin: '600707',
      password: 'GlowWire7',
      backupPassword: 'WireGlow3',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'H4ZEP1X',
      displayName: 'H4zeP1x',
      inviteCode: 'U08-55-3R',
      pin: '600808',
      password: 'HazePix88',
      backupPassword: 'PixHaze4',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'IVYR0CKET',
      displayName: 'IvyR0cket',
      inviteCode: 'U09-55-3R',
      pin: '600909',
      password: 'IvyRocket9',
      backupPassword: 'RocketIvy5',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'J3TC0IL',
      displayName: 'J3tC0il',
      inviteCode: 'U10-55-3R',
      pin: '601010',
      password: 'JetCoil10',
      backupPassword: 'CoilJet6',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'KRYPT0BEE',
      displayName: 'Krypt0Bee',
      inviteCode: 'U11-55-3R',
      pin: '601111',
      password: 'KryptoBee1',
      backupPassword: 'BeeKrypt7',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'LUMENRAY',
      displayName: 'LumenRay',
      inviteCode: 'U12-55-3R',
      pin: '601212',
      password: 'LumenRay12',
      backupPassword: 'RayLumen8',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'MIR4GECAT',
      displayName: 'Mir4geCat',
      inviteCode: 'U13-55-3R',
      pin: '601313',
      password: 'MirageCat3',
      backupPassword: 'CatMirage9',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'N0VAQUILL',
      displayName: 'N0vaQuill',
      inviteCode: 'U14-55-3R',
      pin: '601414',
      password: 'NovaQuill4',
      backupPassword: 'QuillNova1',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'ORB1TWISP',
      displayName: 'Orb1tWisp',
      inviteCode: 'U15-55-3R',
      pin: '601515',
      password: 'OrbitWisp5',
      backupPassword: 'WispOrbit2',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'PR1SMDAWN',
      displayName: 'Pr1smDawn',
      inviteCode: 'U16-55-3R',
      pin: '601616',
      password: 'PrismDawn6',
      backupPassword: 'DawnPrism3',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'QUARKM1NT',
      displayName: 'QuarkM1nt',
      inviteCode: 'U17-55-3R',
      pin: '601717',
      password: 'QuarkMint7',
      backupPassword: 'MintQuark4',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'R1FTSPARK',
      displayName: 'R1ftSpark',
      inviteCode: 'U18-55-3R',
      pin: '601818',
      password: 'RiftSpark8',
      backupPassword: 'SparkRift5',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'SYNTHOWL',
      displayName: 'SynthOwl',
      inviteCode: 'U19-55-3R',
      pin: '601919',
      password: 'SynthOwl19',
      backupPassword: 'OwlSynth6',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'TACHY0N',
      displayName: 'Tachyon',
      inviteCode: 'U20-55-3R',
      pin: '602020',
      password: 'TachyOn20',
      backupPassword: 'OnTachy7',
      tier: UserTier.agent,
    ),
  ];

  static List<OperatorSeed> get all => [...admins, ...developers, ...users];
}
