/// Third operator wave — 5 admins, 3 developers, 20 users.
///
/// Bootstrapped on first install alongside [OperatorRoster.pool] and
/// [OperatorWave2]. DEVELOPER / `developer` remains stricken.
library;

import 'package:polybius/core/constants/app_constants.dart';
import 'package:polybius/core/constants/operator_roster.dart';

/// Wave-3 seeds (admins / developers / agents).
class OperatorWave3 {
  static const List<OperatorSeed> admins = [
    OperatorSeed(
      username: 'V0LTSTAG',
      displayName: 'V0ltStag',
      inviteCode: 'VS1-99-3R',
      pin: '701122',
      password: 'VoltStag91',
      backupPassword: 'StagVolt3',
      tier: UserTier.admin,
    ),
    OperatorSeed(
      username: 'CR1MS0NRX',
      displayName: 'Cr1ms0nRx',
      inviteCode: 'CX2-99-3R',
      pin: '712233',
      password: 'CrimsonRx2',
      backupPassword: 'RxCrimson8',
      tier: UserTier.admin,
    ),
    OperatorSeed(
      username: 'OBS1DIAN',
      displayName: 'Obs1dian',
      inviteCode: 'OD3-99-3R',
      pin: '723344',
      password: 'Obsidian77',
      backupPassword: 'DianObsi5',
      tier: UserTier.admin,
    ),
    OperatorSeed(
      username: 'STORMK3L',
      displayName: 'StormK3l',
      inviteCode: 'SK4-99-3R',
      pin: '734455',
      password: 'StormKel44',
      backupPassword: 'KelStorm6',
      tier: UserTier.admin,
    ),
    OperatorSeed(
      username: 'APEXW0LF',
      displayName: 'ApexW0lf',
      inviteCode: 'AW5-99-3R',
      pin: '745566',
      password: 'ApexWolf9',
      backupPassword: 'WolfApex1',
      tier: UserTier.admin,
    ),
  ];

  static const List<OperatorSeed> developers = [
    OperatorSeed(
      username: 'B1TF0RGE',
      displayName: 'B1tF0rge',
      inviteCode: 'BF1-00-3R',
      pin: '801177',
      password: 'BitForge91',
      backupPassword: 'ForgeBit2',
      tier: UserTier.developer,
    ),
    OperatorSeed(
      username: 'GHOSTASM',
      displayName: 'GhostAsm',
      inviteCode: 'GA2-00-3R',
      pin: '812288',
      password: 'GhostAsm8',
      backupPassword: 'AsmGhost4',
      tier: UserTier.developer,
    ),
    OperatorSeed(
      username: 'ZER0KERN',
      displayName: 'Zer0Kern',
      inviteCode: 'ZK3-00-3R',
      pin: '823399',
      password: 'ZeroKern7',
      backupPassword: 'KernZero3',
      tier: UserTier.developer,
    ),
  ];

  static const List<OperatorSeed> users = [
    OperatorSeed(
      username: 'AUR0RAFOX',
      displayName: 'Aur0raFox',
      inviteCode: 'U21-44-3R',
      pin: '710101',
      password: 'AuroraFx21',
      backupPassword: 'FoxAurora1',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'B0REAL1S',
      displayName: 'B0real1s',
      inviteCode: 'U22-44-3R',
      pin: '710202',
      password: 'Borealis22',
      backupPassword: 'LisBorea2',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'C1NDERSKI',
      displayName: 'C1nderSki',
      inviteCode: 'U23-44-3R',
      pin: '710303',
      password: 'CinderSki3',
      backupPassword: 'SkiCinder3',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'DUSKRAV3N',
      displayName: 'DuskRav3n',
      inviteCode: 'U24-44-3R',
      pin: '710404',
      password: 'DuskRaven4',
      backupPassword: 'RavenDusk4',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'EMBERLYNX',
      displayName: 'EmberLynx',
      inviteCode: 'U25-44-3R',
      pin: '710505',
      password: 'EmberLynx5',
      backupPassword: 'LynxEmber5',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'FROSTW1SP',
      displayName: 'FrostW1sp',
      inviteCode: 'U26-44-3R',
      pin: '710606',
      password: 'FrostWisp6',
      backupPassword: 'WispFrost6',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'GILD3DFIN',
      displayName: 'Gild3dFin',
      inviteCode: 'U27-44-3R',
      pin: '710707',
      password: 'GildedFin7',
      backupPassword: 'FinGilded7',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'HAL0DRIFT',
      displayName: 'Hal0Drift',
      inviteCode: 'U28-44-3R',
      pin: '710808',
      password: 'HaloDrift8',
      backupPassword: 'DriftHalo8',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'IRISNOVA',
      displayName: 'IrisNova',
      inviteCode: 'U29-44-3R',
      pin: '710909',
      password: 'IrisNova29',
      backupPassword: 'NovaIris9',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'JAD3SPARK',
      displayName: 'Jad3Spark',
      inviteCode: 'U30-44-3R',
      pin: '711010',
      password: 'JadeSpark0',
      backupPassword: 'SparkJade1',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'K0IWAVE',
      displayName: 'K0iWave',
      inviteCode: 'U31-44-3R',
      pin: '711111',
      password: 'KoiWave31',
      backupPassword: 'WaveKoi2',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'LUNARB1T',
      displayName: 'LunarB1t',
      inviteCode: 'U32-44-3R',
      pin: '711212',
      password: 'LunarBit32',
      backupPassword: 'BitLunar3',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'MYSTW1RE',
      displayName: 'MystW1re',
      inviteCode: 'U33-44-3R',
      pin: '711313',
      password: 'MystWire33',
      backupPassword: 'WireMyst4',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'NYXFLARE',
      displayName: 'NyxFlare',
      inviteCode: 'U34-44-3R',
      pin: '711414',
      password: 'NyxFlare34',
      backupPassword: 'FlareNyx5',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'OPALR1FT',
      displayName: 'OpalR1ft',
      inviteCode: 'U35-44-3R',
      pin: '711515',
      password: 'OpalRift35',
      backupPassword: 'RiftOpal6',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'PULSEF0X',
      displayName: 'PulseF0x',
      inviteCode: 'U36-44-3R',
      pin: '711616',
      password: 'PulseFox36',
      backupPassword: 'FoxPulse7',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'QUASARK1T',
      displayName: 'QuasarK1t',
      inviteCode: 'U37-44-3R',
      pin: '711717',
      password: 'QuasarKit7',
      backupPassword: 'KitQuasar8',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'RUNEW1SP',
      displayName: 'RuneW1sp',
      inviteCode: 'U38-44-3R',
      pin: '711818',
      password: 'RuneWisp38',
      backupPassword: 'WispRune9',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'SOLST1CE',
      displayName: 'Solst1ce',
      inviteCode: 'U39-44-3R',
      pin: '711919',
      password: 'Solstice39',
      backupPassword: 'SticeSol1',
      tier: UserTier.agent,
    ),
    OperatorSeed(
      username: 'TIDALNYX',
      displayName: 'TidalNyx',
      inviteCode: 'U40-44-3R',
      pin: '712020',
      password: 'TidalNyx40',
      backupPassword: 'NyxTidal2',
      tier: UserTier.agent,
    ),
  ];

  static List<OperatorSeed> get all => [...admins, ...developers, ...users];
}
